CREATE DATABASE quotes

CREATE TABLE BtcBid
	(
		BtcBidId INT NOT NULL IDENTITY (1, 1),
		Microtimestamp BIGINT NOT NULL,
		UsdValue INT NOT NULL,
		Amount DECIMAL(11,8) NOT NULL
	)  ON [PRIMARY]
	
	ALTER TABLE BtcBid
	ADD CONSTRAINT
		PK_BtcBidId PRIMARY KEY CLUSTERED 
		(
			BtcBidId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	ALTER TABLE BtcBid 
	SET (LOCK_ESCALATION = TABLE)

CREATE TABLE BtcAsk
	(
		BtcAskId INT NOT NULL IDENTITY (1, 1),
		Microtimestamp BIGINT NOT NULL,
		UsdValue INT NOT NULL,
		Amount DECIMAL(11,8) NOT NULL
	)  ON [PRIMARY]
	
	ALTER TABLE BtcAsk 
	ADD CONSTRAINT
		PK_BtcAskId PRIMARY KEY CLUSTERED 
		(
			BtcAskId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	ALTER TABLE BtcBid 
	SET (LOCK_ESCALATION = TABLE)

CREATE TABLE EthBid
	(
		EthBidId INT NOT NULL IDENTITY (1, 1),
		Microtimestamp BIGINT NOT NULL,
		UsdValue money NOT NULL,
		Amount DECIMAL(11,8) NOT NULL
	)  ON [PRIMARY]
	
	ALTER TABLE EthBid
	ADD CONSTRAINT
		PK_EthBidId PRIMARY KEY CLUSTERED 
		(
			EthBidId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	ALTER TABLE EthBid 
	SET (LOCK_ESCALATION = TABLE)

CREATE TABLE EthAsk
	(
		EthAskId INT NOT NULL IDENTITY (1, 1),
		Microtimestamp BIGINT NOT NULL,
		UsdValue money NOT NULL,
		Amount DECIMAL(11,8) NOT NULL
	)  ON [PRIMARY]
	
	ALTER TABLE EthAsk 
	ADD CONSTRAINT
		PK_EthAskId PRIMARY KEY CLUSTERED 
		(
			EthAskId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	ALTER TABLE EthAsk
	SET (LOCK_ESCALATION = TABLE)



CREATE TABLE SimulationQuote
	(
		SimulationQuoteId INT NOT NULL IDENTITY (1, 1),
		SimulationQuoteHashIdentifier NVARCHAR(64) NOT NULL,
		OperationChoice INT NOT NULL,
		Coin INT NOT NULL,
		RequestAmount DECIMAL(11,8) NOT NULL,		
		FinalResult DECIMAL(11,8) NOT NULL
	)  ON [PRIMARY]
	
ALTER TABLE SimulationQuote 
ADD CONSTRAINT
		PK_SimulationQuote PRIMARY KEY CLUSTERED 
		(
			SimulationQuoteId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE SimulationQuote 
SET (LOCK_ESCALATION = TABLE)


-- #############################

CREATE TABLE SimulationQuoteValue
(
	SimulationQuoteValueId INT NOT NULL IDENTITY (1, 1),
	SimulationQuoteId INT NOT NULL,
	Amount DECIMAL(11,8) NOT NULL,
	UsdValue money NOT NULL
)ON [PRIMARY]

ALTER TABLE SimulationQuoteValue 
	ADD CONSTRAINT
		PK_SimulationQuoteValueId PRIMARY KEY CLUSTERED 
		(
			SimulationQuoteValueId
		) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE SimulationQuoteValue 
	ADD CONSTRAINT
		FK_SimulationQuote_SimulationQuoteValue FOREIGN KEY
		(
			SimulationQuoteId
		) REFERENCES SimulationQuote
		(
			SimulationQuoteId
		) ON UPDATE  NO ACTION 
		 ON DELETE  NO ACTION 

ALTER TABLE SimulationQuoteValue 
SET (LOCK_ESCALATION = TABLE)





